### ISSUE TITLE
calibrateDepth() error with `dive.model="unimodal"`

### ISSUE THREAD

**Issue by SimonDedman** [spluque/diveMove#5] opened 2019-07-03 00:51 UTC
I have a file of 377882 rows of observations every 2 minutes.
With dive.thr=3 knot.factor = 20:
```
Record is truncated at the beginning and at the end
1 phases detected
5628 dives detected
Error: cannot allocate vector of size 87.2 Gb
```
With dive.thr=10 knot.factor = 3 (same dataset)
```
16667 dives detected
Error in validObject(.Object) : invalid class “diveModel” object: invalid object
for slot "ascent.crit" in class "diveModel": got class "logical", should be or
extend class "numeric"
```
I arbitrarily subsetted my data into just the first 43200 rows and that worked (same parameter settings, 3880 dives detected). But I'm hoping to loop through all my files (up to 400 eventually), some of which are even bigger. Can you think of a way around this big vector issue? If I loop createTDR and calibrateDepth through chunks of each file (e.g. a week of data at a time), that will break any dives going across those splits (not a HUGE problem but slightly annoying) but also the dive.id numbers will reset. Probably something I can code around.

https://drive.google.com/open?id=1Yfh92zXmI1ApPYohenDcCWSuLloyOpFe

Link to example above, then
```
tdrX <- createTDR(time = dfidedupe$DateTimeUTCmin5, depth = dfidedupe$Depth.m., dtime = 120, file = "divemovebigfile")
dcalib <- calibrateDepth(tdrX, dive.thr = 10,  zoc.method = "offset", offset = 0, knot.factor = 3)
```
Thanks!

**Comment by spluque** [comment] 2020-04-07 13:30
Hi Simon, it has been a while I haven't checked in here, but hopefully you found a solution in the meantime.  If not, can you post your work script and sample data file? The link above is for an *.R file but it's not a text file.

**Comment by SimonDedman** [comment] 2020-04-07 16:11
Hi Seb,

Sample data files:
[Small](https://drive.google.com/open?id=1YpZ752ricaGq0GVDm5jb7uDkTQcTrjGw) file, Rds file but will expand to text when opened in RStudio
[Big](https://drive.google.com/open?id=1W_WldLo0jh00LN8bIN9FGoRTaE15XvLM) file, same format

Work script: seems to have been corrupted. But those two lines at the bottom of my example look to be the run code? I never got past this point so I'm a bit rusty!

Cheers,
Simon

**Comment by spluque** [comment] 2020-04-07 16:40
I see no problem running the small sample, but the big one gives an error due to unsorted time stamps.  Please verify the time stamps in this sample and repost it with time stamps in increasing order, making sure the `createTDR` statement runs without errors.

**Comment by SimonDedman** [comment] 2020-04-07 16:55
Ok, just edited that big file to sort by datetime (often there are time disorders due to daylight saving time, leap years, etc). Thanks for looking into this.

**Comment by spluque** [comment] 2020-04-07 17:22
Now you have duplicate values. Make sure the `createTDR` statement runs without errors.

**Comment by SimonDedman** [comment] 2020-04-07 19:38
Apologies, sorted now and reuploaded.

```
testfile <- readRDS("big.Rds") # biggest file in abft, removed all but depth & time, arranged by time (avoid DST issues), remove dupes (DST again)
write.csv(testfile, file = "big.csv", row.names = F)
tdrX <- createTDR(time = testfile$DateTimeUTCmin5,
                  depth = testfile$Depth.m.,
                  file = "big.csv") #works fine
dcalib <- calibrateDepth(tdrX,
                         dive.thr = 10, 
                         zoc.method = "offset",
                         offset = 0,
                         knot.factor = 3)
```

> Record is truncated at the beginning and at the end
> 7 phases detected
> 259691 dives detected
> Error in if (all(Ad1.maybe >= 0)) { : missing value where TRUE/FALSE needed

So a new problem, but gives me hope that sorted the timestamp issue and removing all additional columns (other than maybe an index for re-joining later) might allow this to run.
Please let me know if you have any ideas about this error. Thanks!

**Comment by spluque** [comment] 2020-04-07 22:09
`calibrateDepth` defaults to `dive.model="unimodal"` to detect dive phases.  At least in one of your dives, the method to predict the spline from the model returns a `NA` value for one or more observations in a dive, triggering the error.  This is the first time I've seen this with the unimodal regression dive model implemented many years ago.  I'll try to isolate the problem, find what is causing the `NA` value and fix in the next version.  In the meantime, you can use the less preferable `dive.model="smooth.spline"` (again, see discussion on the help page for `calibrateDepth`), which is really the only reason for using `knot.factor=3` in your call.  That runs without errors, but carefully consider the caveats.

**Comment by SimonDedman** [comment] 2020-04-08 02:45
Interesting, thanks for looking into this. I'll give this a go tomorrow.

**Comment by spluque** [comment] 2020-04-29 08:52
This turned out to be a bug in the uniReg package.  It should be fixed in the next CRAN release of that package.

**Closed as completed by spluque** 2020-04-29 08:52 UTC
Labels: bug
